services:
  web-viralupcom:
    build:
      context: ..
      dockerfile: http.Dockerfile
    container_name: web-dck-viralupcom
    network_mode: "host" # Això fa que agafi la IP de la màquina física
    volumes:
      - ../html:/var/www/viralup
      - ../imatges:/srv/www/viralup/imatges
