services:
  web-viralupcom:
    build:
      context: ..
      dockerfile: http.Dockerfile
    container_name: web-dck-viralupcom
    ports:
      - "8080:80"
    volumes:
      - ../html:/var/www/viralup
      - ../imatges:/srv/www/viralup/imatges
    networks:
      web_subnet:
        ipv4_address: 172.16.21.10

networks:
  web_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.21.0/27
